server:
  port: 9001
spring:
  application:
    name: service-publisher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        weight: 100
#        设置nacos客户端组件打印日志级别，避免循环打印一些不需要的日志
logging:
  level:
    com.alibaba.nacos: warn
