server:
  port: 9004
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: sentinel-demo
  cloud:
    nacos:
      server-addr: 172.17.172.49:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        ds:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            ruleType: flow
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true

