server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  application:
    name: sentinel-demo-client
  cloud:
    nacos:
      server-addr: 172.17.172.49:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080