spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root1997
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    database-schema-update: true
    # 开启历史库
    db-history-used: true
    history-level: audit
