server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_authority?useSSL=false&serverTimezone=GMT
    username: root
    password: root1997
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    pers.lbf: debug
lbf:
  key:
    publicKeyPath: F:\03_JavaProject-IdeaWorkSpace\atr-demo\springBoot-springSecurity-jwt-rsa\authentication-service\src\main\resources\static\key\rsa_key.pub
    privateKeyPath: F:\03_JavaProject-IdeaWorkSpace\atr-demo\springBoot-springSecurity-jwt-rsa\authentication-service\src\main\resources\static\key\rsa_key
