server:
  port: 8848
  servlet:
    context-path: /shiro

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1997
    url: jdbc:mysql://127.0.0.1:3306/shiro_demo1?serverTimezone=GMT%2B8

mybatis:
  configuration:
    map-underscore-to-camel-case: true

